name: Catalina
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - main
      - 'Icepack*'
      - 'ghactions*'
  pull_request:
  release:
    types:
      - created

defaults:
  run:
    shell: /bin/csh {0}

jobs:
  build:
    name: "conda-env Catalina"
    runs-on: macos-latest
    steps:
      - name: reset toolchain to commandlinetools
        run: |
          sudo xcode-select -r
          sudo xcode-select -s /Library/Developer/CommandLineTools
      - name: system info
        shell: /bin/bash {0}
        run: |
          type wget
          type curl
          type csh
          echo "readlink \$(which csh): $(python -c 'import os, sys; print os.path.realpath(sys.argv[1])' $(which csh))"
          echo "csh --version: $(csh --version)"
          echo "uname -a: $(uname -a)"
          echo "sw_vers: $(sw_vers)"
          echo "HOME: $HOME"
          echo "xcrun --show-sdk-path: $(xcrun --show-sdk-path)"
          echo "xcode-select -p: $(xcode-select -p)"
      - name : install miniconda
        shell: /bin/bash {0}
        run: |
          wget https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O ~/miniconda.sh
          bash ~/miniconda.sh -b -p $HOME/miniconda
      - name: clone Icepack
        run: |
          git clone --recurse-submodules --single-branch --depth=1 --shallow-submodules https://github.com/CICE-Consortium/Icepack.git $HOME/icepack
      - name: setup "icepack" conda env
        shell: /bin/bash {0}
        run: |
          cd $HOME && mkdir -p icepack-dirs/runs icepack-dirs/baseline icepack-dirs/input
          source $HOME/miniconda/bin/activate
          conda init zsh
          conda init tcsh
          cd $HOME/icepack
          conda env create -f configuration/scripts/machines/environment.yml
      - name: check conda env (zsh)
        shell: /bin/zsh -i -e {0}
        run: |
          conda activate icepack && type clang && type gfortran && type make
          cat $HOME/miniconda/envs/icepack/etc/conda/activate.d/activate_clang_osx-64.sh
      - name: check conda env
        run: |
          conda activate icepack && type clang && type gfortran && type make
          gfortran --version
          clang --version
          make --version
      - name: check setup case
        run: |
          cd $HOME/icepack
          ./icepack.setup -m conda -e macos -c case0 --pes 1x1 -s diag1
      - name: check setup test
        run: |
          cd $HOME/icepack
          ./icepack.setup -m conda -e macos --test smoke --testid c0
      - name: compile ICEPACK
        run: |
          cd $HOME/icepack
          ./icepack.setup -m conda -e macos -c case1
          cd case1
          ./icepack.build
      - name: download input data
        run: |
          cd $HOME/icepack-dirs/input
          wget https://zenodo.org/record/3728287/files/Icepack_data-20200326.tar.gz && tar xvfz ICEPACK_data-20200326.tar.gz
          pwd
          ls -alR
      - name: run ICEPACK
        run: |
          cd case1
          ./icepack.run
#      - name: run suite
#        run: |
#          cd $HOME/icepack
#          ./icepack.setup -m conda -e macos --suite travis_suite --testid ghamac
#          cd testsuite.ghamac
#          ./results.csh
      - name: write output
#        if: ${{ failure() }}
        run: |
          cd $HOME/icepack
          pwd
          ls -al
          foreach runlog (case*/logs/icepack.runlog.*); echo " "; echo "### tail -100 of $runlog ###' && tail -100 $runlog; end
